name: Deploy
on:
  push:
    branches: ["develop"]
  pull_request:
    types: [closed]
    branches: ["develop"]
    conditions: "${{ github.event.pull_request.merged == true }}"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy code
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/live-stream
            git pull
            npm ci
            npm start
