name: Deploy
on:
  push:
    branches: ["develop"]
  pull_request:
    types: [closed]
    branches: ["develop"]
jobs:
  Deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
        env:
          PATH: $PATH:/home/ubuntu/.nvm/versions/node/v18.15.0/bin/npm
          script: |
           cd ~/live-stream
           git pull
           /home/ubuntu/.nvm/versions/node/v18.15.0/bin/node -v
           /home/ubuntu/.nvm/versions/node/v18.15.0/bin/npm ci
           npm ci
           chmod +x start.sh
           ./start.sh
